spring:
  datasource:
    #url: jdbc:mariadb://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    url: jdbc:h2:mem:test
logging:
  level:
    org:
      hibernate:
        SQL: debug