spring:
  profiles:
    active: dev
    include: secret

  datasource:
    username: root
    password: 1234
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        highlight_sql: true
    hibernate:
      ddl-auto: create
    #    defer-datasource-initialization: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  sql:
#    init:
#      mode: always

  # OAuth2
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

