-- 멤버
insert into member (id, email, password, nickname, role, profile_img, created_at, modified_at, deleted_at)
values (1, 'admin@email.com', '{noop}admin1234', 'admin','ADMIN', null ,now(), now(), null);

insert into member (id, email, password, nickname, role, profile_img, created_at, modified_at, deleted_at)
values (2, 'user@email.com', '{noop}user1234', 'user','MEMBER', null ,now(), now(), null);

insert into member (id, email, password, nickname, role, profile_img, created_at, modified_at, deleted_at)
values (3, 'sonny@email.com', '{noop}sonny1234', 'sonny','MEMBER', null ,now(), now(), null);

-- 상품
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (1, 3, 'Iron Island (Jazireh Ahani)', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.Fusce consequat. Nulla nisl. Nunc nisl.', '도서', 647450, 'http://dummyimage.com/235x100.png/cc0000/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (2, 2, 'Love & Pop', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '생활가전', 416190, 'http://dummyimage.com/157x100.png/dddddd/000000', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (3, 2, 'War of the Arrows (Choi-jong-byeong-gi Hwal)', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '남성의류', 603190, 'http://dummyimage.com/190x100.png/cc0000/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (4, 2, 'Whole Town''s Talking, The (Passport to Fame)', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '디지털기기', 452692, 'http://dummyimage.com/186x100.png/ff4444/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (5, 2, 'Ascent, The (Voskhozhdeniye)', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '남성의류', 650301, 'http://dummyimage.com/207x100.png/5fa2dd/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (6, 2, 'Halfmoon (Paul Bowles - Halbmond)', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '생활가전', 934689, 'http://dummyimage.com/159x100.png/5fa2dd/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (7, 2, 'Evidence of Blood', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '디지털기기', 817394, 'http://dummyimage.com/183x100.png/5fa2dd/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (8, 3, 'Marquis', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.Fusce consequat. Nulla nisl. Nunc nisl.', '생활가전', 331073, 'http://dummyimage.com/191x100.png/5fa2dd/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (9, 2, 'Jeepers Creepers', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '인테리어', 45089, 'http://dummyimage.com/204x100.png/5fa2dd/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (10, 3, 'Adventures of Pinocchio, The', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '생활가전', 848323, 'http://dummyimage.com/181x100.png/ff4444/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (11, 3, 'Cloud 9', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '남성의류', 167511, 'http://dummyimage.com/163x100.png/ff4444/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (12, 3, 'Something''s Gotta Give', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '도서', 618458, 'http://dummyimage.com/111x100.png/ff4444/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (13, 2, 'Ca$h', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '생활가전', 436558, 'http://dummyimage.com/126x100.png/ff4444/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (14, 3, 'Bitch, The (La chienne)', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '인테리어', 11878, 'http://dummyimage.com/230x100.png/ff4444/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (15, 2, 'The Remaining', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '도서', 580674, 'http://dummyimage.com/215x100.png/5fa2dd/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (16, 3, 'Rough House, The', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '생활가전', 599875, 'http://dummyimage.com/133x100.png/5fa2dd/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (17, 3, 'Tommy Boy', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '도서', 193078, 'http://dummyimage.com/116x100.png/dddddd/000000', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (18, 3, 'See No Evil', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '인테리어', 195267, 'http://dummyimage.com/203x100.png/cc0000/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (19, 3, 'Dark Blue World (Tmavomodrý svet)', 'In congue. Etiam justo. Etiam pretium iaculis justo.In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '여성의류', 656699, 'http://dummyimage.com/114x100.png/cc0000/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
insert into item (id, member_id, title, description, category, hope_price, thumbnail_image_url, item_status, created_at, modified_at) values (20, 2, 'Doomsday', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '인테리어', 480836, 'http://dummyimage.com/221x100.png/cc0000/ffffff', 'BIDDING', '2024-01-30 21:55:06', '2024-01-30 21:55:06');
